# Generated by Django 5.1.2 on 2024-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('elo', models.IntegerField(default=1000)),
            ],
            options={
                'db_table': 'Register42_user',
                'managed': False,
            },
        ),
    ]
