# Generated by Django 5.1.1 on 2024-10-04 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
            ],
        ),
    ]
