"""
Django settings for UserManagement project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r2)&k+d9rw^valsfex$-+e(9&l-($t234was%#&!kc41rcvdz5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '10.12.249.34',
    '1A1.42angouleme.fr',
    '1A2.42angouleme.fr',
    '1A3.42angouleme.fr',
    '1A4.42angouleme.fr',
    '1A5.42angouleme.fr',
    '1A6.42angouleme.fr',
    '1A7.42angouleme.fr',
    '1B1.42angouleme.fr',
    '1B2.42angouleme.fr',
    '1B3.42angouleme.fr',
    '1B4.42angouleme.fr',
    '1B5.42angouleme.fr',
    '1B6.42angouleme.fr',
    '1B7.42angouleme.fr',
    '1C1.42angouleme.fr',
    '1C2.42angouleme.fr',
    '1C3.42angouleme.fr',
    '1C4.42angouleme.fr',
    '1C5.42angouleme.fr',
    '1C6.42angouleme.fr',
    '1C7.42angouleme.fr',
    '1D1.42angouleme.fr',
    '1D2.42angouleme.fr',
    '1D3.42angouleme.fr',
    '1D4.42angouleme.fr',
    '1D5.42angouleme.fr',
    '1D6.42angouleme.fr',
    '1D7.42angouleme.fr',
    '1E1.42angouleme.fr',
    '1E2.42angouleme.fr',
    '1E3.42angouleme.fr',
    '1E4.42angouleme.fr',
    '1E5.42angouleme.fr',
    '1E6.42angouleme.fr',
    '1E7.42angouleme.fr',
    '1F1.42angouleme.fr',
    '1F2.42angouleme.fr',
    '1F3.42angouleme.fr',
    '1F4.42angouleme.fr',
    '1F5.42angouleme.fr',
    '1F6.42angouleme.fr',
    '1F7.42angouleme.fr',
    '1G1.42angouleme.fr',
    '1G2.42angouleme.fr',
    '1G3.42angouleme.fr',
    '1G4.42angouleme.fr',
    '1G5.42angouleme.fr',
    '1G6.42angouleme.fr',
    '1G7.42angouleme.fr',
    '2A1.42angouleme.fr',
    '2A2.42angouleme.fr',
    '2A3.42angouleme.fr',
    '2A4.42angouleme.fr',
    '2A5.42angouleme.fr',
    '2A6.42angouleme.fr',
    '2A7.42angouleme.fr',
    '2B1.42angouleme.fr',
    '2B2.42angouleme.fr',
    '2B3.42angouleme.fr',
    '2B4.42angouleme.fr',
    '2B5.42angouleme.fr',
    '2B6.42angouleme.fr',
    '2B7.42angouleme.fr',
    '2C1.42angouleme.fr',
    '2C2.42angouleme.fr',
    '2C3.42angouleme.fr',
    '2C4.42angouleme.fr',
    '2C5.42angouleme.fr',
    '2C6.42angouleme.fr',
    '2C7.42angouleme.fr',
    '2D1.42angouleme.fr',
    '2D2.42angouleme.fr',
    '2D3.42angouleme.fr',
    '2D4.42angouleme.fr',
    '2D5.42angouleme.fr',
    '2D6.42angouleme.fr',
    '2D7.42angouleme.fr',
    '2E1.42angouleme.fr',
    '2E2.42angouleme.fr',
    '2E3.42angouleme.fr',
    '2E4.42angouleme.fr',
    '2E5.42angouleme.fr',
    '2E6.42angouleme.fr',
    '2E7.42angouleme.fr',
    '2F1.42angouleme.fr',
    '2F2.42angouleme.fr',
    '2F3.42angouleme.fr',
    '2F4.42angouleme.fr',
    '2F5.42angouleme.fr',
    '2F6.42angouleme.fr',
    '2F7.42angouleme.fr',
    '2G1.42angouleme.fr',
    '2G2.42angouleme.fr',
    '2G3.42angouleme.fr',
    '2G4.42angouleme.fr',
    '2G5.42angouleme.fr',
    '2G6.42angouleme.fr',
    '2g7.42angouleme.fr',
    '3A1.42angouleme.fr',
    '3A2.42angouleme.fr',
    '3A3.42angouleme.fr',
    '3A4.42angouleme.fr',
    '3A5.42angouleme.fr',
    '3A6.42angouleme.fr',
    '3A7.42angouleme.fr',
    '3B1.42angouleme.fr',
    '3B2.42angouleme.fr',
    '3B3.42angouleme.fr',
    '3B4.42angouleme.fr',
    '3B5.42angouleme.fr',
    '3B6.42angouleme.fr',
    '3B7.42angouleme.fr',
    '3C1.42angouleme.fr',
    '3C2.42angouleme.fr',
    '3C3.42angouleme.fr',
    '3C4.42angouleme.fr',
    '3C5.42angouleme.fr',
    '3C6.42angouleme.fr',
    '3C7.42angouleme.fr',
    '3D1.42angouleme.fr',
    '3D2.42angouleme.fr',
    '3D3.42angouleme.fr',
    '3D4.42angouleme.fr',
    '3D5.42angouleme.fr',
    '3D6.42angouleme.fr',
    '3D7.42angouleme.fr',
    '3E1.42angouleme.fr',
    '3E2.42angouleme.fr',
    '3E3.42angouleme.fr',
    '3E4.42angouleme.fr',
    '3E5.42angouleme.fr',
    '3E6.42angouleme.fr',
    '3E7.42angouleme.fr',
    '3F1.42angouleme.fr',
    '3F2.42angouleme.fr',
    '3F3.42angouleme.fr',
    '3F4.42angouleme.fr',
    '3F5.42angouleme.fr',
    '3F6.42angouleme.fr',
    '3F7.42angouleme.fr',
    '3G1.42angouleme.fr',
    '3G2.42angouleme.fr',
    '3G3.42angouleme.fr',
    '3G4.42angouleme.fr',
    '3G5.42angouleme.fr',
    '3G6.42angouleme.fr',
    '3G7.42angouleme.fr',
    'localhost:42424',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Register42',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UserManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UserManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'zeph',
        'PASSWORD': 'zeph1234',
        'HOST': 'postgres',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/usr/src/app/logs/django.log',
            'formatter': 'simple',
        },
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/usr/src/app/logs/debug.log',
            'formatter': 'simple',
        },
        'print_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/usr/src/app/logs/print.log',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['django_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['debug_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'print': {
            'handlers': ['print_file'],
            'level': 'INFO',
            'propagate': True,
        }
    },
}